---
#
# Ansible managed
#
repository:
  description: Install SCL on your system.
  homepage: https://buluma.github.io/
  topics: scl, repository, installer, packages, ansible, molecule, tox, playbook
